FROM node:7.2.1-wheezy
# https://hub.docker.com/_/node/
# https://github.com/nodejs/docker-node/

# https://github.com/Yelp/dumb-init
RUN wget --quiet https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dumb-init_1.0.1_amd64.deb
RUN dpkg -i dumb-init_*.deb

RUN apt-get update && apt-get install apt-transport-https

# Install yarn package manager
RUN wget -qO - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update -qq && apt-get install -y -qq yarn

EXPOSE 8000

# Forcing reset of source:
RUN echo "{{ansible_date_time.epoch}}" /build_time.txt
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY source/ .

RUN git log -n 1 --pretty=format:"%H" > /git_hash.txt

CMD [ "dumb-init", "echo", "THIS IMAGE IS SUPPOSED TO BE EXTENDED WITH config IMAGE" ]
